// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TunaPiano;

#nullable disable

namespace TunaPiano.Migrations
{
    [DbContext(typeof(TunaPianoDBContext))]
    [Migration("20240910223558_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.Property<int>("GenresId")
                        .HasColumnType("integer");

                    b.Property<int>("SongsId")
                        .HasColumnType("integer");

                    b.HasKey("GenresId", "SongsId");

                    b.HasIndex("SongsId");

                    b.ToTable("GenreSong");
                });

            modelBuilder.Entity("TunaPiano.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 35,
                            Bio = "Hailing from Nashville, Jackson Ridge blends traditional country sounds with a modern twist. Known for his deep, gravelly voice and heartfelt ballads, Jackson's songs about love, heartache, and small-town life have made him a fan favorite in the country music scene.",
                            Name = "Jackson Ridge"
                        },
                        new
                        {
                            Id = 2,
                            Age = 27,
                            Bio = "Texas native Sadie Mae Walker is a rising star in the country music scene. Her energetic performances and relatable lyrics about southern life have propelled her to the top of country charts. She brings a youthful, modern edge to traditional country sounds.\r\n",
                            Name = "Sadie Mae Walker"
                        },
                        new
                        {
                            Id = 3,
                            Age = 29,
                            Bio = "An indie rock artist from Portland, Milo Rivers combines raw guitar riffs with introspective lyrics. His music is known for its emotional depth and unique sound, making him a standout in the underground indie scene.",
                            Name = "Milo River"
                        },
                        new
                        {
                            Id = 4,
                            Age = 24,
                            Bio = "A pop sensation from Los Angeles, Layla Sky's catchy melodies and upbeat dance tracks have made her a household name. Her infectious energy and glittering stage presence have won over fans around the world, making her one of pop music’s brightest stars.",
                            Name = "Layla Sky"
                        },
                        new
                        {
                            Id = 5,
                            Age = 42,
                            Bio = "Ezra Cole is a seasoned blues artist from Memphis, known for his soulful voice and masterful guitar skills. With roots in traditional Delta blues, his music explores themes of hardship and resilience, capturing the heart of the blues genre.",
                            Name = "Ezra Cole"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Country"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Indie Rock"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Pop"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Blues"
                        });
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Album")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<int>("Length")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album = "Highway to Home",
                            ArtistId = 1,
                            Length = 225,
                            Title = "Whiskey on the Wind"
                        },
                        new
                        {
                            Id = 2,
                            Album = "American Dreamer",
                            ArtistId = 1,
                            Length = 242,
                            Title = "Small Town Sundown"
                        },
                        new
                        {
                            Id = 3,
                            Album = "Texas Heart",
                            ArtistId = 2,
                            Length = 230,
                            Title = "Lone Star Night"
                        },
                        new
                        {
                            Id = 4,
                            Album = "Honky-Tonk Heartbeat",
                            ArtistId = 2,
                            Length = 250,
                            Title = "Dust on My Boots"
                        },
                        new
                        {
                            Id = 5,
                            Album = "Broken Horizons",
                            ArtistId = 3,
                            Length = 260,
                            Title = "Echoes in the Rain"
                        },
                        new
                        {
                            Id = 6,
                            Album = "Under the Bridge",
                            ArtistId = 3,
                            Length = 238,
                            Title = "Neon Nights"
                        },
                        new
                        {
                            Id = 7,
                            Album = "Neon Glow",
                            ArtistId = 4,
                            Length = 210,
                            Title = "Shimmering Lights"
                        },
                        new
                        {
                            Id = 8,
                            Album = "Cosmic Beat",
                            ArtistId = 4,
                            Length = 220,
                            Title = "Starlight City"
                        },
                        new
                        {
                            Id = 9,
                            Album = "Midnight Blues",
                            ArtistId = 5,
                            Length = 315,
                            Title = "River of Sorrow"
                        },
                        new
                        {
                            Id = 10,
                            Album = "Deep Waters",
                            ArtistId = 5,
                            Length = 365,
                            Title = "Broken Strings"
                        });
                });

            modelBuilder.Entity("GenreSong", b =>
                {
                    b.HasOne("TunaPiano.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunaPiano.Models.Song", null)
                        .WithMany()
                        .HasForeignKey("SongsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TunaPiano.Models.Song", b =>
                {
                    b.HasOne("TunaPiano.Models.Artist", null)
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TunaPiano.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
